# starship config
# ref: https://starship.rs/config

format = """
$time\
$shlvl\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$custom\
$cmd_duration\
$jobs\
$battery\
$container\
$shell\
$kubernetes\
$character"""

# right_format = '$time'

continuation_prompt = '▶▶'

command_timeout = 1000

### NERD FONT SYMBOLS PRESET BEGIN

[aws]
symbol = ' '

[buf]
symbol = ' '

[c]
symbol = ' '

[conda]
symbol = ' '

[dart]
symbol = ' '

[directory]
read_only = ' '
truncate_to_repo = false
truncation_length = 5

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[git_branch]
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
symbol = ' '

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = '⌘ '

[hg_branch]
symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = ' '

[meson]
symbol = '喝 '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[os.symbols]
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '﯑ '
Gentoo = ' '
HardenedBSD = 'ﲊ '
Illumos = ' '
Linux = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = ' '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = ' '
Solus = 'ﴱ '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = ' '

[package]
symbol = ' '
format = '\[[$symbol$version]($style)\] '

[python]
symbol = ' '

[rlang]
symbol = 'ﳒ '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[scala]
symbol = ' '

[spack]
symbol = '🅢 '

### NERD FONT SYMBOLS PRESET END

[sudo]
format = '[as $symbol]($style)'
disabled = false

[time]
format = '[$time]($style) '
style = 'dimmed'
disabled = false

[cmd_duration]
# show_notifications = true
min_time = 1_000
# show_milliseconds = true
format = '[祥$duration]($style) '

[shlvl]
symbol = '→'
format = '[\($shlvl\)]($style) '
style = 'dimmed'
disabled = false

[kubernetes]
format = '[\[$symbol$context( \($namespace\))\]]($style) '
disabled = false
style = 'dimmed'
detect_folders = ['environments']

[kubernetes.context_aliases]
'arn:aws:eks:us-west-2:\d+:cluster/(?P<var_cluster>[\w-]+)' = '$var_cluster'
