# starship config
# ~/.config/starship.toml
# ref: https://starship.rs/config

format = """
$shlvl\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$custom\
$cmd_duration\
$jobs\
$battery\
$container\
$shell\
$kubernetes\
$character"""

# $time\
# $sudo\

# right_format = '$time'

continuation_prompt = '▶▶'

command_timeout = 1000

add_newline = false

[sudo]
format = '[as $symbol]($style)'
disabled = false

[time]
format = '[$time]($style) '
style = 'dimmed'
disabled = false

[cmd_duration]
# show_notifications = true
min_time = 1_000
show_milliseconds = true
format = '[$duration]($style) '
style = 'yellow'

[shlvl]
symbol = '→'
format = '[\($shlvl\)]($style) '
style = 'dimmed'
disabled = false

[kubernetes]
format = '[\[$symbol$context( \($namespace\))\]]($style) '
disabled = false
style = 'dimmed'
detect_folders = ['environments']

[kubernetes.context_aliases]
'arn:aws:eks:us-west-2:\d+:cluster/(?P<var_cluster>[\w-]+)' = '$var_cluster'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
style = "cyan"
read_only = " 󰌾"
truncate_to_repo = true
truncation_length = 3
repo_root_style = "39"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "40"

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
